import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { rank, related, score, splitWords, stem, titleHits, type LibraryItem } from '../retrieval';
import { extractHeadings } from '../headings';
import RetrievalDemo, { type DemoLabels, type DemoRanking } from '../RetrievalDemo';
import ArchiveIndex from '../ArchiveIndex';
import enMessages from '../../../../../../messages/en.json';
import bnMessages from '../../../../../../messages/bn.json';

jest.mock('@/i18n/navigation', () => ({
  Link: ({ children, href, ...rest }: React.PropsWithChildren<{ href: string }>) => (
    <a href={href} {...rest}>
      {children}
    </a>
  ),
}));

beforeAll(() => {
  window.matchMedia = ((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => undefined,
    removeListener: () => undefined,
    addEventListener: () => undefined,
    removeEventListener: () => undefined,
    dispatchEvent: () => false,
  })) as typeof window.matchMedia;
});

const item = (key: string, title: string, excerpt = '', tags: string[] = []): LibraryItem => ({
  key,
  type: 'blog',
  slug: key,
  href: `/resources/blog/${key}`,
  title,
  excerpt,
  tags,
  date: '2026-01-01',
});

const LIB = [
  item('a', 'Choosing a web app', 'A framework for the decision', ['web']),
  item('b', 'Measuring AI quality', 'Evals that tell you whether it is getting better', ['ai']),
  item('c', 'Unrelated', 'Nothing here', []),
];

describe('retrieval scoring', () => {
  it('stems lightly', () => {
    expect(stem('measured')).toBe('measur');
    expect(stem('measuring')).toBe('measur');
    expect(stem('apps')).toBe('app');
    expect(stem('ai')).toBe('ai');
  });

  it('scores 2 per title term, 1 per description/tag term, normalised', () => {
    expect(score(['ai', 'quality'], LIB[1])).toBe(1);
    expect(score(['better'], LIB[1])).toBe(0.5);
    expect(score(['web', 'nothing'], LIB[0])).toBe(0.5);
    expect(score([], LIB[0])).toBe(0);
  });

  it('ranks best first with stable ties and is deterministic', () => {
    const r = rank(['ai', 'measure'], LIB);
    expect(r.map((x) => x.key)).toEqual(['b', 'a', 'c']);
    expect(rank(['ai', 'measure'], LIB)).toEqual(r);
  });

  it('finds related items, never itself, and drops zero overlap', () => {
    const r = related(LIB[1], LIB);
    expect(r.every((x) => x.key !== 'b' && x.score > 0)).toBe(true);
  });

  it('marks matching title words', () => {
    const words = splitWords('Measuring AI quality');
    expect(titleHits(['ai'], 'Measuring AI quality').map((i) => words[i])).toEqual(['AI']);
  });
});

describe('table of contents extraction', () => {
  it('pulls the h2 headings out of the compiled content', () => {
    for (const file of ['blogs', 'guides']) {
      // .velite is generated by the dev/build pipeline; nothing to check before it exists.
      const path = join(process.cwd(), '.velite', `${file}.json`);
      if (!existsSync(path)) continue;
      const docs = JSON.parse(readFileSync(path, 'utf8')) as { content: string }[];
      for (const doc of docs) {
        const hs = extractHeadings(doc.content);
        expect(hs.length).toBeGreaterThan(0);
        for (const h of hs) {
          expect(doc.content).toContain(`id:"${h.id}"`);
          expect(h.text.length).toBeGreaterThan(0);
        }
      }
    }
  });
});

const LABELS: DemoLabels = {
  label: 'Retrieval',
  example: 'Over this library',
  chipsLabel: 'Example questions',
  queryLabel: 'Question',
  termsLabel: 'Key terms',
  resultsLabel: 'Results',
  ranking: 'Ranking',
  pause: 'Pause',
  play: 'Play',
  note: 'Word overlap',
  topMatch: 'Top match',
};

describe('RetrievalDemo', () => {
  const queries = [
    { chip: 'Quality', text: 'How do we know the AI is getting better?', terms: ['ai', 'better'] },
    { chip: 'Web', text: 'Web or mobile?', terms: ['web'] },
  ];
  const rankings: DemoRanking[] = queries.map((q) => {
    const r = rank(q.terms, LIB);
    return {
      order: r.map((x) => x.key),
      scores: Object.fromEntries(r.map((x) => [x.key, { value: x.score, label: x.score.toFixed(2) }])),
      hits: Object.fromEntries(LIB.map((it) => [it.key, titleHits(q.terms, it.title)])),
    };
  });

  it('server-renders the finished ranking of the first question as links', () => {
    render(
      <RetrievalDemo
        queries={queries}
        items={LIB.map((it) => ({ key: it.key, href: it.href, title: it.title, typeLabel: 'Blog' }))}
        rankings={rankings}
        labels={LABELS}
      />,
    );
    const links = within(screen.getByRole('list')).getAllByRole('link');
    expect(links.map((a) => a.getAttribute('href'))).toEqual(rankings[0].order.map((k) => `/resources/blog/${k}`));
    expect(screen.getByRole('button', { name: 'Quality' })).toHaveAttribute('aria-pressed', 'true');
  });

  it('pins a question from its chip', () => {
    render(
      <RetrievalDemo
        queries={queries}
        items={LIB.map((it) => ({ key: it.key, href: it.href, title: it.title, typeLabel: 'Blog' }))}
        rankings={rankings}
        labels={LABELS}
      />,
    );
    fireEvent.click(screen.getByRole('button', { name: 'Web' }));
    expect(screen.getByRole('button', { name: 'Web' })).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByRole('status')).toHaveTextContent('Top match: Choosing a web app');
  });
});

describe('ArchiveIndex', () => {
  it('filters rows by tag and reports the count', () => {
    const rows = LIB.map((it, i) => ({
      key: it.key,
      href: it.href,
      n: String(i + 1),
      title: it.title,
      excerpt: it.excerpt,
      dateLabel: '1 January 2026',
      dateTime: it.date,
      tags: it.tags.map((id) => ({ id, label: id })),
    }));
    render(
      <ArchiveIndex
        rows={rows}
        tags={[
          { id: 'web', label: 'Web', count: 1 },
          { id: 'ai', label: 'AI', count: 1 },
        ]}
        labels={{ filter: 'Filter', all: 'All', showing: 'Showing {shown} of {total}', empty: 'None', tags: 'Tags' }}
        bengaliDigits={false}
      />,
    );
    expect(screen.getByRole('status')).toHaveTextContent('Showing 3 of 3');
    fireEvent.click(screen.getByRole('button', { name: /Web/ }));
    expect(screen.getByRole('button', { name: /Web/ })).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByRole('status')).toHaveTextContent('Showing 1 of 3');
    expect(screen.getAllByRole('heading', { level: 2 })).toHaveLength(1);
  });
});

describe('Resources messages', () => {
  type Q = { chip: string; text: string; terms: string[] };
  const en = (enMessages as unknown as { Resources: { retrieval: { queries: Q[] } } }).Resources;
  const bn = (bnMessages as unknown as { Resources: { retrieval: { queries: Q[] } } }).Resources;

  it('uses the same key terms in both locales (the content is English)', () => {
    expect(bn.retrieval.queries.map((q) => q.terms)).toEqual(en.retrieval.queries.map((q) => q.terms));
    expect(en.retrieval.queries.length).toBeGreaterThanOrEqual(3);
  });
});

describe('ArticleShell', () => {
  const path = join(process.cwd(), '.velite', 'blogs.json');
  const run = existsSync(path) ? it : it.skip;

  run('renders a real post: one h1, a TOC that links to every section, the MDX body', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const ArticleShell = require('../ArticleShell').default as typeof import('../ArticleShell').default;
    const [doc] = JSON.parse(readFileSync(path, 'utf8')) as { title: string; excerpt: string; content: string }[];
    const { container } = render(
      <ArticleShell
        id="t"
        kicker="Blog"
        back={{ href: '/resources/blog', label: 'All posts' }}
        title={doc.title}
        dek={doc.excerpt}
        meta={[{ label: '1 January 2026', dateTime: '2026-01-01' }]}
        tags={['AI']}
        code={doc.content}
        labels={{ toc: 'On this page', tags: 'Tags' }}
      />,
    );
    expect(screen.getAllByRole('heading', { level: 1 })).toHaveLength(1);
    const toc = screen.getByRole('navigation', { name: 'On this page' });
    const targets = within(toc)
      .getAllByRole('link')
      .map((a) => a.getAttribute('href')?.slice(1));
    expect(targets.length).toBeGreaterThan(0);
    for (const id of targets) expect(container.querySelector(`.rs-prose [id="${id}"]`)).not.toBeNull();
  });
});
